#include "serialization/Message_test.cpp"
#include "crypto/Srp_test.cpp"
#include "database/Connection_test.cpp"
#include "serialization/MessagePaddr_test.cpp"
#include "serialization/MessageDecoder_test.cpp"
#include "crypto/Sha1_test.cpp"
#include "serialization/opcodes/Acceptdata_test.cpp"
